### ISSUE TITLE
Duplicate response in stops

### ISSUE THREAD

**Issue by alexandru-calinoiu** [gov-ithub/info-transport-api#1]
I seem to get duplicate stops when calling `/v0.1/{city_id}/stops`

**Comment by mnemonicflow** [comment]
Added direction field to disambiguate
>     {
>         "direction": "forward",
>         "latitude": 45.671123,
>         "name": "Baza MTTC",
>         "id": "BAZA_MTTC_D",
>         "longitude": 25.640974
>     },
>     {
>         "direction": "backward",
>         "latitude": 45.67132,
>         "name": "Baza MTTC",
>         "id": "BAZA_MTTC_I",
>         "longitude": 25.641604
>     },
